# Generated by Django 5.1.6 on 2025-03-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plan',
            name='check_limit',
            field=models.IntegerField(default=0),
        ),
    ]
