# Generated by Django 5.1.6 on 2025-03-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fintech', '0002_remove_plan_created_at_remove_plan_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
